// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EfForeignKeyIssue.Models;

public partial class Schedule
{
    public int PkId { get; set; }

    public string Description { get; set; }

    public virtual ICollection<DbTask> Groups { get; set; } = new List<DbTask>();
}